<?xml version="1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hexapod_description)/urdf/robot_parameters.xacro" />
    <xacro:include filename="$(find hexapod_description)/urdf/links_joints.xacro" />

    <xacro:macro    name = "leg_l" 
                    params = "body_leg_dx body_link_name coxa_link_name thigh_link_name tibia_link_name" >

        <!-- Coxa description -->

        <xacro:simple_joint name="${coxa_link_name}" 
                    type="revolute"
                    axis_xyz="0 0 1"
                    origin_rpy="0 0 0"
                    origin_xyz="${body_leg_dx} ${body_legs_dy} ${body_legs_dz}" 
                    parent="${body_link_name}"
                    child="${coxa_link_name}" />

        <xacro:simple_mesh_link name="${coxa_link_name}"
                    origin_rpy="0 0 0" 
                    origin_xyz="${coxa_dx} ${coxa_dy} ${coxa_dz}"
                    com_xyz="${coxa_com_x + coxa_dx} ${-coxa_com_y + coxa_dy} ${coxa_com_z + coxa_dz}"
                    mass="0.011"
                    ixx="0.001827" ixy="-0.000062" ixz="0.000016" 
                    iyy="0.001496" iyz="0.000151" 
                    izz="0.001137"
                    mesh_file="package://hexapod_description/meshes/coxa_l"
                    mesh_scale="0.001 0.001 0.001" />

        <!-- Thigh description -->

        <xacro:simple_joint    name="${thigh_link_name}" 
                    type="revolute" 
                    axis_xyz="1 0 0"
                    origin_rpy="0 ${pi} 0"
                    origin_xyz="${coxa_dx + coxa_thigh_dx} ${coxa_dy - coxa_thigh_dy} ${coxa_dz - coxa_thigh_dz}"
                    parent="${coxa_link_name}" 
                    child="${thigh_link_name}" />

        <xacro:simple_mesh_link name="${thigh_link_name}"
                    origin_rpy="0 ${pi} 0"
                    origin_xyz="${thigh_dx} ${thigh_dy} ${thigh_dz}"
                    com_xyz="${-thigh_com_x + thigh_dx} ${thigh_com_y + thigh_dy} ${thigh_com_z}"
                    mass="0.004"
                    ixx="0.000844" ixy="0" ixz="-0.000015" 
                    iyy="0.000959" iyz="0" 
                    izz="0.001661"
                    mesh_file="package://hexapod_description/meshes/thigh"
                    mesh_scale="0.001 0.001 0.001" />

        <!-- Leg 2 (lf) tibia description -->

        <xacro:simple_joint    name="${tibia_link_name}" 
                    type="revolute" 
                    axis_xyz="1 0 0"
                    origin_rpy="0 0 0"
                    origin_xyz="0 ${thigh_dy * 2} 0"
                    parent="${thigh_link_name}"
                    child="${tibia_link_name}" />

        <xacro:simple_mesh_link name="${tibia_link_name}"
                    origin_rpy="0 ${pi} 0"
                    origin_xyz="${tibia_dx} ${-tibia_dy} ${-tibia_dz}"
                    com_xyz="${-tibia_com_x + tibia_dx} ${tibia_com_y - tibia_dy} ${tibia_com_z + tibia_dz}"
                    mass="0.011"
                    ixx="0.003738" ixy="0" ixz="-0.000029" 
                    iyy="0.003919" iyz="0" 
                    izz="0.00059"
                    mesh_file="package://hexapod_description/meshes/tibia"
                    mesh_scale="0.001 0.001 0.001" />
                    
    </xacro:macro>

    <xacro:macro    name = "leg_r" 
                    params = "body_leg_dx body_link_name coxa_link_name thigh_link_name tibia_link_name" >

        <!-- Coxa description -->

        <xacro:simple_joint    name="${coxa_link_name}" 
                    type="revolute" 
                    axis_xyz="0 0 1"
                    origin_rpy="0 0 0" 
                    origin_xyz="${body_leg_dx} -${body_legs_dy} ${body_legs_dz}" 
                    parent="${body_link_name}"
                    child="${coxa_link_name}" />

        <xacro:simple_mesh_link name="${coxa_link_name}"
                    origin_rpy="0 0 0" 
                    origin_xyz="${coxa_dx} -${coxa_dy} ${coxa_dz}"
                    com_xyz="${coxa_com_x + coxa_dx} ${coxa_com_y - coxa_dy} ${coxa_com_z + coxa_dz}"
                    mass="0.011"
                    ixx="0.001827" ixy="0.000062" ixz="0.000016" 
                    iyy="0.001496" iyz="-0.000151"
                    izz="0.001137"
                    mesh_file="package://hexapod_description/meshes/coxa_r"
                    mesh_scale="0.001 0.001 0.001" />

        <!-- Thigh description -->

        <xacro:simple_joint    name="${thigh_link_name}" 
                    type="revolute" 
                    axis_xyz="1 0 0"
                    origin_rpy="0 0 0" 
                    origin_xyz="${coxa_dx + coxa_thigh_dx} ${-coxa_dy + coxa_thigh_dy} ${coxa_dz - coxa_thigh_dz}" 
                    parent="${coxa_link_name}" 
                    child="${thigh_link_name}" />

        <xacro:simple_mesh_link name="${thigh_link_name}"
                    origin_rpy="0 0 0" 
                    origin_xyz="${-thigh_dx} ${-thigh_dy} ${-thigh_dz}"
                    com_xyz="${thigh_com_x - thigh_dx} ${thigh_com_y - thigh_dy} ${thigh_com_z}"
                    mass="0.004"
                    ixx="0.000844" ixy="0" ixz="-0.000015" 
                    iyy="0.000959" iyz="0" 
                    izz="0.001661"
                    mesh_file="package://hexapod_description/meshes/thigh"
                    mesh_scale="0.001 0.001 0.001" />

        <!-- Tibia description -->

        <xacro:simple_joint    name="${tibia_link_name}" 
                    type="revolute" 
                    axis_xyz="1 0 0"
                    origin_rpy="0 0 0" 
                    origin_xyz="0 ${-thigh_dy * 2} 0"
                    parent="${thigh_link_name}" 
                    child="${tibia_link_name}" />

        <xacro:simple_mesh_link name="${tibia_link_name}"
                    origin_rpy="0 0 0" 
                    origin_xyz="${-tibia_dx} ${tibia_dy} ${tibia_dz}"
                    com_xyz="${tibia_com_x - tibia_dx} ${tibia_com_y - tibia_dy} ${tibia_com_z + tibia_dz}"
                    mass="0.011"
                    ixx="0.003738" ixy="0" ixz="-0.000029" 
                    iyy="0.003919" iyz="0" 
                    izz="0.00059"
                    mesh_file="package://hexapod_description/meshes/tibia"
                    mesh_scale="0.001 0.001 0.001" />
        
    </xacro:macro>

</robot>