# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# ============================================================
# coxa controllers

# Position Controllers ---------------------------------------
j_c1_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_rf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_c1_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_lf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_c1_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_rm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_c1_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_lm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_c1_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_rr
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_c1_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_c1_lr
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# ============================================================
# thigh controllers

# Position Controllers ---------------------------------------
j_thigh_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_thigh_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_thigh_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_thigh_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_thigh_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rr
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_thigh_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lr
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# ============================================================
# tibia controllers

# Position Controllers ---------------------------------------
j_tibia_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_tibia_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lf
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_tibia_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_tibia_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lm
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_tibia_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rr
  pid: {p: 1000.0, i: 0.01, d: 0.01}

# Position Controllers ---------------------------------------
j_tibia_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lr
  pid: {p: 1000.0, i: 0.01, d: 0.01}