# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# ============================================================
# coxa controllers

# Position Controllers ---------------------------------------
j_coxa_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_rf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_coxa_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_lf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_coxa_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_rm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_coxa_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_lm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_coxa_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_rr
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_coxa_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_coxa_lr
  pid: {p: 100.0, i: 0.01, d: 0.1}

# ============================================================
# thigh controllers

# Position Controllers ---------------------------------------
j_thigh_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_thigh_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_thigh_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_thigh_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_thigh_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_rr
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_thigh_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_thigh_lr
  pid: {p: 100.0, i: 0.01, d: 0.1}

# ============================================================
# tibia controllers

# Position Controllers ---------------------------------------
j_tibia_rf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_tibia_lf_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lf
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_tibia_rm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_tibia_lm_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lm
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_tibia_rr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_rr
  pid: {p: 100.0, i: 0.01, d: 0.1}

# Position Controllers ---------------------------------------
j_tibia_lr_position_controller:
  type: effort_controllers/JointPositionController
  joint: j_tibia_lr
  pid: {p: 100.0, i: 0.01, d: 0.1}